### ISSUE TITLE
HaCVillagerAgriResearchHouse crash

### ISSUE THREAD

**Issue by Kehaan** [defeatedcrow/HeatAndClimateMod#106]
Hello

I am currently getting the following "HaCVillagerAgriResearchHouse" crash. Which my guess is from Heat and Climate. The crash happens when creating a world, and also when trying to logging into the world again. So just wanted to report it here:

[crash-2019-06-09_12.17.34-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/3269419/crash-2019-06-09_12.17.34-server.txt)

**Comment by defeatedcrow** [comment]
Hello.  Thank you for your report. This issue will be fixed in the next update.

This problem seems to be caused by the block that the village structure contains is turned off in the configuration. By turning on "EnableAdvancedBuildingBlocks" in module.cfg, it is possible to avoid a crash as the first aid.

**Comment by Kehaan** [comment]
Thanks for the quick reply :)
