### ISSUE TITLE
JER_profile Crash with H&CMod

### ISSUE THREAD

**Issue by iamweirdie** [defeatedcrow/HeatAndClimateMod#125]
Hello,

I ran a JER_profile [ described here [https://github.com/way2muchnoise/JustEnoughResources/wiki/Profiling](https://github.com/way2muchnoise/JustEnoughResources/wiki/Profiling) ] in my single player world and the game crashed. Twice.

[crash-2019-09-12_01.01.23-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/3608248/crash-2019-09-12_01.01.23-server.txt)
[crash-2019-09-12_19.18.16-server.txt](https://github.com/defeatedcrow/HeatAndClimateMod/files/3608211/crash-2019-09-12_19.18.16-server.txt)

This was with
forge-1.12.2-14.23.5.2838-universal.jar
HeatAndClimateLib_1.12.2-3.1.1.jar 
HeatAndClimateMod_1.12.2-3.1.3.jar
jei_1.12.2-4.15.0.268.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
JEROreIntegration-1.12.2-1.1.0.jar

There are other mods on the list, but i thought these might be the most relevant.

https://github.com/way2muchnoise/JustEnoughResources/issues/201
i have also sent the other author this issue to be safe.

**Comment by defeatedcrow** [comment]
Hello, iamweirdie.
Thank you for your report.

But unfortunately this is a crash caused by another mod and there is nothing I can do.

For some reason the server side player is lost and it seems that it is not loading properly. In the first report, HaC has crashed about unlocking the advancement. In the second report, the vanilla server failed to load. (That is, it happens between other mods and vanilla, and HaC is not involved.)

I think that the cause that is preventing the vanilla server from loading properly needs to be removed.
