### ISSUE TITLE
HaC clothes and Vic's Modern Warfare incompatibility: NullPointerException

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#136]
#### Mod version:
HaCLib Version: HeatAndClimateLib_1.12.2-3.2.3
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.5
[Vic's Modern Warfare Mod](https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod) Version:
Both mw_2.0-0.4.1_mc1.12.2 (latest version) and mw-1.11.7.7-mc1.12.2 (latest Release) were tested,
and both of them led to game crash.

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both singleplayer and multiplayer.

#### Installed mods:
![](https://user-images.githubusercontent.com/28519848/72797526-3de12d00-3c7c-11ea-839c-51c5a305efe8.png)

## Link to full crash log
Crash with mw_2.0-0.4.1_mc1.12.2 (latest version) installed:
https://paste.dimdev.org/jahahuyihe.mccrash

Crash with mw-1.11.7.7-mc1.12.2 (latest Release) installed:
https://paste.ubuntu.com/p/fKZ3RzRKk3/

#### How to reproduce:

1. Wear any of HaC's clothes(HaC's armor is not included);
2. Put any of Vic's Modern Warfare Mod's gun on the main hand;
3. Game crashes immediately.

I have read these two crash-reports before I post this issue.
This may be because Vic's Modern Warfare modified the player model.
Vic's Modern Warfare is always complaint about conflicting with mods related to player model,
and it is closed source,
So if you think this is Vic's fault, you may tell me your opinion and then close this issue.

Looks forward to your reply!
Thanks in advance!

**Comment by defeatedcrow** [comment]
Hello! Thank you for your report.

I read your crash report, and in conclusion, this cannot be fixed on my part.

The crash is occurring while a model of HaC's clothing gains the angle of the player's arms and body. That happened because vanilla lacked the information it should have. Perhaps the replacement model provided by Vic's is incompatible with the vanilla model, or it seems that some fields are missing.
(I guess, they control the orientation of the player's arm to force the player to hold the gun. And probably compatibility was broken at that point.)

I hope they fix it. But, (as I did,) modifying the BipedModel seems to be difficult, hampered by vanilla hardcoding. So, even if they give up fixing, I sympathize with them.

Sorry for not helping.

**Comment by RisingInIris2017** [comment]
You are indeed a warm-hearted modder I have ever met :)
Thanks for your explanation!
