### ISSUE TITLE
Texture broke: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#137]
#### Mod version:

HaCLib Version: HeatAndClimateLib_1.12.2-3.2.3
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.5

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both Singleplayer and Multiplayer.

#### Installed mods:

![](https://user-images.githubusercontent.com/28519848/72961436-02657080-3dec-11ea-93f1-e302c2ebdbe0.png)

## Link to full crash log

Crash report after F3+T: https://paste.dimdev.org/oficuzenod.mccrash
Crash report after changing game language: https://paste.dimdev.org/bejusimika.mccrash

#### How to reproduce:

Simply press F3+T to reload resources. Then game crashes.
After this, Join a multiplayer game, or enter a local world save. 
A world of blocks and items losing their textures can be seen,
But some blocks keep their textures, such as vanilla glasses,
Shulker boxes, HaC's wind vanes, and so on.

This issue can be solved by restarting the game manually. 
I used [VanillaFix](https://github.com/DimensionalDevelopment/VanillaFix), so my game will not close automatically when an exception is thrown.
But I think this is a bug indeed, so I post this issue here.

#### Pictures:

![2020-01-23_14 18 09](https://user-images.githubusercontent.com/28519848/72962827-6be77e00-3df0-11ea-8b00-4cd3d5ecd552.png)
![2020-01-23_14 19 05](https://user-images.githubusercontent.com/28519848/72962830-6e49d800-3df0-11ea-8743-2bafc840d951.png)

Looks forward to your reply!
Thanks in advance!

**Comment by defeatedcrow** [comment]
Hello.

Minecraft internally outputs the textures of all blocks to one large png file (as before ver1.4). If that fails, it will look as shown in your image.
Since the file size varies depending on the play environment, it may be failed due to the play environment or computer load. (Since it is fixed by performing the same operation again, it is presumed to be a temporary cause.)
Entities are not affected by these. TileEntity too. So chests and windmills are displayed correctly.

**Comment by RisingInIris2017** [comment]
Thanks for your explanation! It is a minor bug as we have seen, so I will close this issue temporarily and this issue may be a reference when another player run into this issue :)
