### ISSUE TITLE
[Bug] Crossbow shoots continuously without charging

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#139]
#### Mod version:

HaCLib Version: HeatAndClimateLib_1.12.2-3.2.3
HaCMod Version: HeatAndClimateMod_1.12.2-3.2.5

#### Forge version:

14.23.5.2847

#### Singleplayer or Multiplayer:
Singleplayer

#### Installed mods:

![](https://user-images.githubusercontent.com/28519848/72961436-02657080-3dec-11ea-93f1-e302c2ebdbe0.png)

#### How to reproduce:
Simply hold an HaC crossbow and right-click again and again,
the crossbow will fire like a machine gun.

I have a screen record for this issue, here is the link:
https://imgur.com/QwdU3bG

This issue leads to the fact that Crossbows are too over-powered. With this feature, anyone could deal a huge amount of damage as soon as he has enough bolts.
This is a bit weird, and I have no idea about how to deal with this issue.

Look forward your reply!
Thanks in advance!

**Comment by defeatedcrow** [comment]
Bowguns can fire arrows simply by pulling the trigger. (This is the correct specification.)Naturally stronger than a vanilla bow. The cost of Bowguns and bolts are higher than a vanilla bow, as it is made of metal.

Players who criticize mod elements as OP are universal, but following them is pointless. For them, there is a config to adjust the damage of HaC's shooting weapon. Please use it.

**Comment by RisingInIris2017** [comment]
Oh, thanks for your explanation!
~~But I still have some questions, so I referred to Wikipedia:
https://ja.wikipedia.org/wiki/%E5%BC%A9#%E6%80%A7%E8%83%BD
Crossbows need their users to pull it much harder than pulling a bow; if a crossbow is not charged  fully, it should not shoot as far as a fully charged one does.~~
Did you mean "Bowguns" from Monster Hunter?
I have got it, maybe it is better to configure it.

I have another suggestion. Now our Crossbows are able to shoot as long as there are bolts in the player's inventory. So if a player got a crossbow with "Infinity" enchantment, or he has filled his inventory with bolts(26x64 bolts, 1664 bolts in total), he will be able to shoot continuously and infinitely without reload his crossbow. 
I have read the [Light Bowgun from Monster Hunter World Wiki](https://monsterhunterworld.wiki.fextralife.com/Light+Bowgun). I have not played this game before, but I think even this Bowgun from MHW needs a little amount of time to reload, instead of keeping shooting until all ammo is used.
My suggestion is to limit the number of bolts a crossbow can shoot before its recharge. 
Crossbow should recharge, or "Cool-down" for every 5, or 8, or 10 shoots. 
I do not have idea about how to programming this, maybe you can design Crossbows to use "Bunch of bolts" instead of bolts, and every time a crossbow consumes a bunch of bolts, it should recharge for several ticks, consume another bunch, and then continue to shoot. Just like a modern rifle and its magazine.
This is only my personal opinion, you may design this crossbow as you like.
Looks forward your reply!
Thanks for your patience!

**Comment by defeatedcrow** [comment]
This mod is built on my thoughts. Realizing your ideas is one of the great rewards of modder. Therefore, I am not open to others about the design policy of this project.

Make your ideas to realized with your effort and responsibility. Your idea cannot be realized using my resources.
Also keep in mind that this mod is not tailored to your play style or progress. Any suggestions that may affect other players are basically at my sole discretion. Because many “good suggestors” do not have the ability to care for other players.

***

Regarding Bowgan, your consideration is wrong. This performance is made for the play of Minecraft and does not divert other games.

I'm creating mods with one motivation for frustration with vanilla (as many other modders do).
About with this crossbow, I don't agree with vanilla's combat balance, so I've set it as strong as I need.

In this game, players have to face countless monsters as alone.
In addition, it is not just a “one-to-many” game, but a monster's coordinates shifted by 1/3 ～ 1/2 block due to serious server lag (since ver1.3.X).
However, the developer nerfed theplayer  melee attack and repeated the upward correction of the monster.

The game lacks shooting and area attacks (especially vanilla), and developers don't like enhancing or increasing existing systems. Therefore, many mods have tried to make up for it.
For players who are not good at or don't like fighting monsters, shooting attacks that require accurate aim can't safely handle multiple monsters (even if their DPS is high enough). I'm creating that items for such players. They require a high item tier (at the price of high performance). Crossbows require Tier 2 metal and muskets require Tier 3 metal. Also, some area attacks have been implemented for magic cards using rare items, these are support for battle.
The game also does not present any new difficulties as the player's resources evolve. It's tough for early players and boring for advanced players. Probably lack of level design.

What makes a crossbow feel OP is simply not maintaining balance in your current playing environment. If so, you should modify your environment at your own risk. You can tweak the crossbow or try other mods that add more difficult stages.

***

PS.
You seem to be filling your inventory with bolts (1,664). Perhaps you lack the consideration of the core system of this game (inventory is a limited player resource, "filling the inventory" is itself the cost of the item).
Some items in HaC require players to occupy and reduce their inventory instead of consuming items. That is the intended specification.

**Comment by RisingInIris2017** [comment]
Sorry for my abrupt manner! I have read your comment and got your idea about it.
I am not meaning to offend you. Please forgive me for my improper words.
Thanks for your patience, writing this long and explicit explanation!

I am indeed like your great mod. Maybe I will run into other issues in the future,
and I hope I can get your help at that time, just like you have done before. 
Not out of selfishness, but your help is needed indeed :)
Wish you a nice day!
Love you ❤️

**Comment by defeatedcrow** [comment]
As a mod surpport, I simply provided the necessary explanation. If you look through some emotions in my writing, you are probably wrong.
Naturally kids are immature, so I won't get angry at it.

I encourage you to make your own ideas, not by criticism, but by favor. Frustration is a good motivation for creation. If you have a concrete idea (like you), you can make a good work.
