### ISSUE TITLE
Some ores aren't showing

### ISSUE THREAD

**Issue by debbinghail** [defeatedcrow/HeatAndClimateMod#149]
![2020-03-19_16 32 38](https://user-images.githubusercontent.com/62373160/77042587-47c6a880-69ff-11ea-9917-a85709f3a24c.png)
some ores are not showing (like a "石英ダイヤ鉱石")
how to fix it?
and my mod version is HeatAndClimateLib-1.12.2_3.2.6 and HeatAndClimateMod-1.12.2_3.3.0

**Comment by debbinghail** [comment]
ah, wait, it just updated. so its fine.
but, could you update your wiki?

**Comment by defeatedcrow** [comment]
Since v3.0.0, the documentation for this mod uses on-game display (Advancement and JEI information) instead of an external wiki.
Wikis are not currently maintained. Because I don't have any resources for that. This project is no reward, no warranty. Player comfort is not supported. Use at your own risk.

**Comment by debbinghail** [comment]
Understood. Thank you very much.
