### ISSUE TITLE
aquiring viscera

### ISSUE THREAD

**Issue by ACIIL** [defeatedcrow/HeatAndClimateMod#15]
I am trying to make cheese and following the crafting path with JEI. I am lost, where is viscera acquired?   Is viscera a mob drop?

**Comment by defeatedcrow** [comment]
Yes, viscera is a mob drop. That will be dropped if any animal is overkilled by shooting.

**Comment by ACIIL** [comment]
Thank you. After many shooting attempts with Bow, i got viscera drops. Yeah!   It was about 20+ kills before the first viscera dropped. 

The "shoot" conditional may be the reason i never saw it in the drop list for "Just Enough Resources (JER)".   I also use a AI mod that causes mobs to try and dodge arrows (special_ai), maybe that was affecting the drop loot table indirectly as mobs dodge.

**Comment by defeatedcrow** [comment]
Thank you for your report. It is probably not supported for JER. I use Forge 's LivingDeathEvent for dropping viscera, so it may not be reflected in the mob drop route information.

I am considering delete the restriction of "shoot" for making it easier to obtain it. Since the viscera increace, measures will be necessary. For example ... Increasing dishes of viscera.

**Comment by ACIIL** [comment]
Thank you for the tip.   Feel free to close this when you think you balanced the drop.

**Comment by ACIIL** [comment]
I see the item drops from normal mob kills now. Probability best to close this.
