### ISSUE TITLE
HeatAndClimateMod 1.12.2 3.3.3 Can't collect bedrock with Titanium Pickaxe

### ISSUE THREAD

**Issue by Tayu0404** [defeatedcrow/HeatAndClimateMod#157]
# Environment
## Forge
* 14.23.5.2847
## Mods
* HeatAndClimateLib_1.12.2-3.3.1.jar
* HeatAndClimateMod_1.12.2-3.3.3.jar

# Explanation
In previous versions, you could collect more than Y2 bedrock with a titanium pickaxe, but it wasn't possible in 3.3.3.
I tested it in an environment that only uses this mod, but couldn't collect bedrock.
I think it's a bug because there was no such change in the release log.

I look forward to your Mod. Thank you.

**Comment by defeatedcrow** [comment]
Hello
This issue still seems to need clarification. 

First, the bug cannot be reproduced yet. It works fine in my test environment.
If it is reproducible, it will be corrected.

True, this feature hasn't changed in recent versions.
This function operates under the following conditions.
・ Player sneaks and right-click.
・ Y altitude is 2 or more.
・ The pickaxe tier is 4 or higher.
・ Coordinates that the player is allowed to edit. (This is a vanilla feature for blocks that cannot be edited by the player due to some game modes, restrictions on server commands and plugins.)

If you meet all of the above, it's probably a bug I haven't discovered. I would appreciate it if you could tell me the details.

**Comment by Tayu0404** [comment]
I'm sorry.I forgot to press shift.
I'm sorry to bother you

Thank you very much

**Comment by defeatedcrow** [comment]
Thank you for the explanation.
I'm glad I solved it. Enjoy the mod :D
