### ISSUE TITLE
Can I apply ore generation setting only to Twilight forest?

### ISSUE THREAD

**Issue by yunomic** [defeatedcrow/HeatAndClimateMod#160]
It works strange with HeatAndClimate ore generating in twilight forest and I  tried to change that but it seemed not to be able to apply the setting to world by each dimensions.
I want to disable ore generate only to twilight forest but not to normal world.
![2020-05-18_02 33 30](https://user-images.githubusercontent.com/65309248/82159675-fc2f5e80-98ca-11ea-8cde-61a2c307f7ef.png)

**Comment by defeatedcrow** [comment]
HaC veins are similarly generated for all dimensions except the Nether End.
Twilight Forest is a mod with a special Y altitude above ground, so veins will be generated near it. (This is not strange. It is due to the Twilight Forest specification.)
HaC does not have individual setting items by dimension. If you want it, It's nesessary to use the API to create an Addon that can do that.

Alternatively, (if you just want to hide it from the surface), blocks added to the "Blockgen Disable List" in worldgan.cfg can no longer be replaced by veins. (ex, grass or dirt block can be exclude with it.)
