### ISSUE TITLE
[Suggestion] Add compat with Rockhounding mod: Chemistry

### ISSUE THREAD

**Issue by gatoborrachon** [defeatedcrow/HeatAndClimateMod#175]
I already asked to the dev of Rockhounding if he could add compat with your mod, he said that he will see it but he also told me that he lacks of time, idk if he will be able to add it so that's why i come here to ask.

that mod, like Heat and Climate, adds a lot of chemical processes and machines to do them, but there are many compounds in common that aren't compatible, only one example could be Nitrogen, when i use a Paper Pack in a fluid tank with Nitrogen from HaC it gives me Nitrogen Pack, but with Nitrogen from Rockhounding it doesn't works.

but also idk if you could see more great ways to add more compat than just make the (same) fluids compatible for recipes, like the catalysts, the compounds, the alloys, etc

Link: https://www.curseforge.com/minecraft/mc-mods/rockhounding-mod-chemistry/

**Comment by defeatedcrow** [comment]
I don't make it. The simple reason I only make plugins for mods that I like. Therefore, plugins of that mod (I don't know the contents of it) will not be considered.
Plug-ins will only be considered if I play with the mod repeatedly myself and have a good understanding of its implementation and content.

One more thing: Fluid compatibility will not be implemented in the future, because Forge does not support a way to implement it, and therefore it is not possible to implement it.

**Comment by gatoborrachon** [comment]
ok, sorry
