### ISSUE TITLE
Add percentage GUI offset

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#190]
When changing the position of the HaC GUI, the config has what may be pixel values for offset.

The problem is that the offset will be different on different window or monitor or if fullscreen or not.
Can you please make it work consistent with all screen size.
Perhaps by using a percentage of size as offset.

**Comment by defeatedcrow** [comment]
I will consider the ability to change position depending on the current window size.

Your idea (% notation) is a non-major in other mods and may confuse other players. I will not adopt it.

It does not support "all" screen sizes.
I'll consider fixing it, but we will continue to make no guarantees about malfunctions caused by the play environment. (It's the same as the traditional license.) This kind of support is something we don't usually do and is over-requested. (I think that the supported operating environment is usually limited even for general paid content.)

**Comment by ghost** [comment]
The issue is that the default position gets interfered with by achievement and other messages. Even with default minecraft settings.
So I felt it best to move the postion of GUI to top out of the way of messages. But placement was not consistent due to window size. 
Even if the GUI could be offset a fixed amount from top of window that would work.
Even better would be offsets from a chosen side, so you could select to offset top/bottom, left/right.

**Comment by defeatedcrow** [comment]
There are no plans to implement any number of detailed configs for GUI positioning.
We accept issues, but you cannot specify how to resolve the issue.

In particular, we reject proposals that reduce the degree of freedom in positioning (by choosing from top, bottom, left, and right). "It's convenient to be at the top of the screen" is optimized idea for your environment , there are some environments where it isn't, and the adjustments will continue to be detailed.
Do you think that is less difficult to implement? It's a mistake and we don't accept speculative advice.

**Comment by defeatedcrow** [comment]
It has been fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/50bad9c08bfb7de2169aa9b4605ffbbf3fc77ce5.

You can also update core.cfg during gameplay using the following commands. (Excluding some items.)
Please use it.
/climate config core

Thank you.
