### ISSUE TITLE
HAC ore blocks override Twilight Forest Mod's boss spawner block

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#207]
Forge version:
14.23.5.2855

HAC Mod version:
1.12.2-3.6.8

HAC Lib version:
1.12.2-3.6.6

How to reproduce:
Simply put HAC Mod and Twilight Forest Mod together in a modpack,
then search Twilight Forest dimension for boss spawners.
You will find some spawners for Hydra and Alpha Yeti have become HAC ores.

If you need screenshots, I will provide it later, sorry for any inconvinience caused by me!
Thanks for your help in advance!

**Comment by defeatedcrow** [comment]
Special blocks, such as those with TileEntity or no drop items, are not replacement targets for ore generation. But otherwise, if the implementation is internally indistinguishable from a naturally generated normal block, HaC will not be able to identify it. They can be individually excluded by the player.

There is already a blacklist option for adding blocks that the player does not want to replace. Please use it.
("Blockgen Disable List" in worldgen.cfg)

**Comment by RisingInIris2017** [comment]
> There is already a blacklist option for adding blocks that the player does not want to replace. Please use it.
> ("Blockgen Disable List" in worldgen.cfg)

Got it. Thanks for your explanation!
