### ISSUE TITLE
Player kicked by server: critical exception handling a packet on channel dcs_climate

### ISSUE THREAD

**Issue by RisingInIris2017** [defeatedcrow/HeatAndClimateMod#210]
Forge version:
14.23.5.2855

HAC Mod version:
1.12.2-3.6.8

HAC Lib version:
1.12.2-3.6.6

How to reproduce:
This issue randomly occurs, and I have not found how to reproduce it at 100% probability yet.

Description of the problem:
Players may suddenly be kicked out of the server, but game does not crash.
Check the `latest.log` collected from their clients, we can see such a log printed at the same time they were kicked:
https://paste.ubuntu.com/p/mzVmnWWqJq/

Full mod list:
https://paste.ubuntu.com/p/XqsyRnxnbh/

I am confused about such an issue. Not so sure about how to reproduce it, but every day there are some players running into this issue. It is quite annoying.
It is deeply appreciated if you would help me to fix it.
Thanks in advance!

**Comment by defeatedcrow** [comment]
Hello.
This is not a HaC crash, a vanilla method called by HaC.
It is inferred that the TileEntity on the server side that send packet does not exist at the coordinates of the TileEntity on the client side. This may be due to a mismatch in save data.
Perhaps you can fix it by removing the offending block of coordinates (if you have a crash report, you may get specific coordinates) from the world.

**Comment by RisingInIris2017** [comment]
> Hello.
> This is not a HaC crash, a vanilla method called by HaC.
> It is inferred that the TileEntity on the server side that send packet does not exist at the coordinates of the TileEntity on the client side. This may be due to a mismatch in save data.
> Perhaps you can fix it by removing the offending block of coordinates (if you have a crash report, you may get specific coordinates) from the world.

Oh I see. I may write a reply after doing a thorough examination on those chunks which frequently invoke this issue.
