### ISSUE TITLE
[Suggestion] Chinfuju Mod Compatibility 

### ISSUE THREAD

**Issue by UberbeastX** [defeatedcrow/HeatAndClimateMod#239]
Hello Crow I know this may be a pain to ask for bur I was wondering if there could be come compatibility between this mod and the chinfuju+japanese block mod as far as cooking goes, because I'm not able to cook the chinfuju mod foods with heat and climate things.

Like in the chinfuju mod I can cook something in a frying pan hen it's on a furnace or chinfuju stove but when I put it on the heat and climate equivalents it doesn't work. Also I was wondering if climate smelting could be added for the chinfuju raw food blocks to cook them. If I can do this through configs sorry for wasting your time.

**Comment by defeatedcrow** [comment]
Hello.
Rather than worrying about my pain, I encourage you to check the license and support rules. About compatibility with other mods, only mods included in the https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/resources/ReadMe_Plugin.txt file are supported. Other mods are not compatible.

By the way, your request can be solved with the existing HaC config.
If you want to set the temperature for HaC in the block of other mods, you can add the block ID to "block_climate_parameter".
In addition, HaC climate refining, hot pot dishes, machine recipes, etc. can be added or deleted by the config file respectively. It is in the "recipe" directory.

Also, the contents of chinjufu mod cannot be operated from HaC. Those requests should be contacted to the author of the chinjufu mod or made by yourself.
I have no plans to create compatibility for the chinjufu mod. There are two reasons:
One is that HaC simply contains only the content I like. Elements that I don't like will not be implemented.
The other is that Kantai Collection has a license that clearly states the prohibition of "made a derivative work include a game system". Japanese dojin creators are often nervous about that and I don't want to put my project at risk either.
(Anyway, I don't like that game so much, so I won't be involved in it in the future.)
