### ISSUE TITLE
Induction motor

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#26]
Induction motor will take any amount of FU/RF and always produce 128 torque.

**Comment by defeatedcrow** [comment]
The induction motor automatically stops when it can not be carried out to the torque outlet. So if you want to stop it, stop the transmission of torque at the exit. (For example, the gearbox stops when it receives the RS signal.)

**Comment by ghost** [comment]
Sorry report was unclear. 
Induction motor will take any amount of rf/tick as input and always give 128 torque as output. For example 1rf/tick input will create 128 torque output, but also 100 rf/tick will create 128 torque output. The amount of torque is not proportional to amount of RF. In addition, changing the RF->torque ratio in config does not seem to be affecting induction motor.
Tested using Forestry RF generators (bio gas and clockwork), Animania (hamster wheel) RF generator, and all Thermal expansion RF generators. All inputs always create 128 torque output.
as second example connecting a Hamster wheel (20rf/tick) to a induction motor and then the induction motor to the Dynamo will produce much more than 20rf/tick

**Comment by defeatedcrow** [comment]
Thank you for the detailed explanation.
Next time I will fix the design of this machine. (Perhaps It failed calculate the influx amount of RF and ForgeUnit.）

**Comment by ghost** [comment]
I thought RF=FU in 1.12?
Also, thank you for looking into the issue!
I wish more mods used torque but unfortunately conversion is needed.

**Comment by defeatedcrow** [comment]
Sorry, there was one description missing about torque.
HaC machines will only update tiles and packets every 20 ticks in order to reduce PC load.
The machine receives and accumulates up to 1280 RF during 20 ticks, and outputs it periodically. (Its mechanism is similar to a capacitor.) So **this machine requires 1280 RF / 20 tick** for the maximum output.(Please carefully, that is not "1280 RF / 1 tick")

There is a problem with the current source.
- The overflowing RF disappears.
- RF and FU are not consumed correctly.

I am fixing them now. However, as RF and FU receive processing is duplicated, I may stop supporting FU.

----
**The following sentences are a digression:**
This machine was created in Nov 2016, and at that time I was missing the following information for implementing FU.
- Energy Rate
I still do not know the correct answer. So I assumed RF = FU, but made it changeable by player as config. (However, because it caused the bug, I will stop this design.)
- Output Active
There are both "output-active" energy (that the exporting side actively outputs energy) and "input-active"energy (that the receiving side actively aspirates energy). I did not know which of that should be implemented. So, this machine implemented an aspiration of FU from 6 side adjacent machine as the input-active type. (Perhaps this was a mistake.)

Now that these implementation examples have increased, I also consider reworking this machine as RF = FU.

**Comment by defeatedcrow** [comment]
Fixed it in 866a9d4.

**Comment by ghost** [comment]
Thank you very much for the detailed explanation and the fix!
