### ISSUE TITLE
Plan for data-driven recipes?

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#275]
Glad to hear that you are porting HaC to 1.19.2!

May I ask if the recipe system in 1.19.2 will be datapack driven (like those json recipes for shaped crafting)? It would be way more easier for modpack makers or tweaker mods like CraftTweaker or KubeJS if it's data-driven.

**Comment by defeatedcrow** [comment]
Hello.
It's a necessity for me too, so I'm considering it. Those recipes are currently located in the config directory, and changing the directory will enable datapack support.
However, it has not been realized because we do not know how to implement it. We are currently exploring elements that are not described in the Forge documentation, including many other 1.19.2 coding. Unfortunately, I think datapack support will be a long-term challenge.

**Comment by Prunoideae** [comment]
Ok, I understand, bumping version from 1.12.2 to 1.19.2 is quite a challenge, it also took me a while to realize how things work in higher versions, hope you will get that soon.

I'd recommend you to refer to someone else's code to get quick and better understanding of mechanisms: [FTBICRecipes](https://github.com/FTBTeam/FTB-Industrial-Contraptions/blob/287f00fbb43150ebe3dd7572f10983f081a31bf6/src/main/java/dev/ftb/mods/ftbic/recipe/FTBICRecipes.java#L25)

You can start by the repo, mainly focusing on the implementation of `BasicGeneratorFuelRecipe` and `BasicGeneratorFuelRecipeSerializer`, also, [this](https://github.com/FTBTeam/FTB-Industrial-Contraptions/blob/287f00fbb43150ebe3dd7572f10983f081a31bf6/src/main/java/dev/ftb/mods/ftbic/recipe/RecipeCache.java#L86) is also quite important.

HaC is a pretty good mod, I hope that these can help in your porting.

**Comment by defeatedcrow** [comment]
Thanks for the info. However, if the license is not clear, HaC will never see it. The example project has a closed license, so I can't use it.
I believe that validating the Forge code is the only way to be sure now. Also, this project is not aimed at mod packers, so I'm in no hurry to implement it for them. Datapack support is required but not a high priority.
