### ISSUE TITLE
IPlantable seeds

### ISSUE THREAD

**Issue by ghost** [defeatedcrow/HeatAndClimateMod#30]
Is it possible for seeds to implement Iplantable? Other mods require interface for compatibility,

**Comment by defeatedcrow** [comment]
I'll implement with next update.
However, EnumPlantType does not have appropriate parameters for water lily or seaweed. It probably will not work properly.

**Comment by defeatedcrow** [comment]
It implemented at defeatedcrow/HeatAndClimateLib@2ab4741
It was implemented in ClimateCropBase.class and ClimateDoubleCropBase.class which is the base class of many crops.

**Comment by ghost** [comment]
Thank you very much! Can confirm it works with the mod Steve's Carts reborn, allowing the farming module to plant HAC seeds successfully. Will close issue as success.

**Comment by MaskedBird** [comment]
Just as a follow up, this was required because of getItem() instanceof IPlantable; check found in multiple mods, using Steve's Carts Reborn as test to see if implementation was successful. Some mods did not use interface but use it to identify what is a plant and what is not. Thank you for this again, it has been very useful.
