### ISSUE TITLE
obtaining iron is op

### ISSUE THREAD

**Issue by captcookie** [defeatedcrow/HeatAndClimateMod#32]
So I was mining and the ores that spawn with heat and iron turn into iron dust or copper ore and so forth. They spawn on the surface. I didnt see a config file, but literally obtaining way too much too fast.

**Comment by defeatedcrow** [comment]
The generation rate of each ore vein can be changed by config. You can change to the probability that you feel right. You can also disable generation of it by setting the probability to 0.
See config (defeatedcrow/climate/worldgen.cfg).

In this mod, each veins is limited by the biome. There is a possibility that unfortunate players will be stuck due to extreme biome bias. So, I have raised the generation probability high.

Another suggestion: There is an API on vein generation. (defeatedcrow.hac.main.api.orevein.IVeinTableRegister) You can use this api to change the composition of the vein.
