### ISSUE TITLE
About world generation and lags

### ISSUE THREAD

**Issue by DLumina** [defeatedcrow/HeatAndClimateMod#36]
![2018-07-22_15 26 05](https://user-images.githubusercontent.com/38756860/43043372-fe0d9dd8-8dc4-11e8-9951-df475b3cbe33.png)
Hi, I've just added this mod to my modpack, but when I was testing I noticed something wrong on the upper-left corner: over 4,600 trunks are loaded and this caused a serious lag. I Googled for this and found an possible reason here:

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

Actually I am not sure whether the HaC caused the lag..But I think the vein generation may caused the problem since they do not generate in the center of the trunk. Hope you can fix it, and thank you for your contributions to this mod!

Update: the following line was founded in my latest.log:

> [15:07:32] [Server thread/WARN]: HeatAndClimateMod loaded a new chunk [-23, -1] in dimension 0 (overworld) while populating chunk [-22, 0], causing cascading worldgen lag.

[latest.log](https://github.com/defeatedcrow/HeatAndClimateMod/files/2216810/latest.log)

(It seems like most of the problems are caused by the ruins mod...)

**Comment by defeatedcrow** [comment]
Hi Zhiyu-Yang, Thanks for the comment.

> https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

The problem was discovered in March 2017 and I fixed it last year. Currently, that problem does not apply to HaC.

> [15, 07: 32] [Server thread / WARN]: HeatAndClimateMod loaded a new chunk [-23, -1] in dimension 0 (overworld) while populating chunk [-22, 0], causing cascading worldgen lag.

For this log, this is intentional concerning the generation of Caravanserai. Structures other than Caravanserai do not cause it.

---
By the way, HaC certainly does some heavy processing. You can suppress them with the following config. Please see core.cfg:

- "Enable Vanilla Block Recipe"
HaC increases the block update for natural change of the vanilla blocks. This is the heaviest process in HaC. If you set it false, you can stop it.

- "Enable DropItem Recipe"
This is a config for natural change of drop items. If it is set false, it can be suppressed.

In addition, if you think that HaC's Worldgen is unnecessary, see module.cfg:

- B: EnableWorldgen
This config stops generation of all world structures by HaC. Reduce processing load of world generation.

**Comment by DLumina** [comment]
I'm so sorry about that... I do not know about Java and I just guessed tabout this... Thank you for your answer and your contributions to this great mod!
