### ISSUE TITLE
Craft Tweaker Support

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#40]
Any plans for Craft Tweaker support? I was trying to remove a recipe but it appears the mod is putting it back in during load.
Thanks

**Comment by defeatedcrow** [comment]
For craft recipes, I feel it is appropriate to replace to json files (as recommended by Forge). It is under planning. However, some NBT-sensitive recipes will be registered in the old way. It does not correspond to Tweaker.

For machine recipes, they can already be modified by API. It is recommended to use a modding approach.
Since Craft Tweaker support causes dependency on Craft Tweaker, it should be independent as Addon. I can not create it, so it takes a long time to try.

**Comment by defeatedcrow** [comment]
At 446240a All recipes have been replaced by json!

**Comment by LEWeee** [comment]
A lot of modpack makers don't feel comfortable with altering a mods files, fearing they might get sued, especially since the license says that:
>You can redistribute this mod's **unmodified** package to modpack or multiplayer server.

Also, I think that a lot of people would appreciate the ability to add or remove climate smelting recipes

**Comment by defeatedcrow** [comment]
There is no need to rewrite the files in the package to modify the recipe,.
This mod exposes an API for recipes, and climate smelting recipes can be changed through the API (from add-ons or other mods). If you use that method, you do not need to change to the HaC package. Also, add-on samples are available on gist.
https://gist.github.com/defeatedcrow/b587e212fdd188aa68c4d912162f6c9d

The safe way shouldn't be difficult, I think modpacker has enough technical power to make it. 

This mod doesn't get any rewards for publishing, so the increase in users and packers will only increase the developer's burden. I'll do some cooperation, but I'll limit the response to requests.
