### ISSUE TITLE
World Ticking

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#42]
I'm getting a lot of this in single player and multiplayer server.

![2018-08-24_19 53 33](https://user-images.githubusercontent.com/30163566/44614349-a4d48b00-a7d7-11e8-88f2-d3478762ab10.png)

**Comment by defeatedcrow** [comment]
Sorry, I do not know the tool, so I do not know the meaning of that image.
Since it can not identify the problem part, I interpreted it as an issue of "dissatisfaction from players with unknown PC capability".

This mod has heavy processing for terrain generation and block update, and drop item update. They can be turned off by the player. I can not guarantee the operation with any PC capability. It is assumed that players will adjust it according to PC capabilities.
So I recommend to turn off **"core.cfg / Enable Vanilla Block Recipe"** and **"core.cfg / Enable DropItem Recipe"** in config. (It is planned to turn off default by next update.) In addition, you can delete terrain generation by turning off "module.cfg / world". All vein generation will be deleted.
In order to satisfy me, I added those functions with awareness. So I may  open it only to players who can agree with the current situation by using a password or config.

**Comment by AdaraChristine** [comment]
The pic is the output of a mod called lag goggles https://minecraft.curseforge.com/projects/laggoggles. LagGoggles is a profiler where you can see timings in the world and fps. The pic is the output from a WORLD scan and shows WORLD ticking. I HAVE turned off "core.cfg / Enable Vanilla Block Recipe" and "core.cfg / Enable DropItem Recipe" in the config. I would like to use the magic module so i do not wish to turn the ores off.

**Comment by defeatedcrow** [comment]
Thank you for telling me a good tool. It seems useful for development. I'll try to find the cause part with it.

As a first aid, I made some changes to reduce the frequency of block update. https://github.com/defeatedcrow/HeatAndClimateLib/commit/595c5a70b2369901db3b5522d8e91252fa79b3b6 and a16e93d
These will be reflected in the next update. There is probably a small improvement on lag.

**Comment by AdaraChristine** [comment]
You are Welcome! I really like your mod and the work you are doing, and i hope my input helps you to have a successful project :)

**Comment by defeatedcrow** [comment]
Until https://github.com/defeatedcrow/HeatAndClimateLib/commit/683832d339fbc1e71e8bfdc6168dab367ca78d71, I made some fix for reduce lag. At v2.5.8, the lag will be reduced in vanilla world. (That image was taken in the forest biome.)
![2018-08-26_15 34 45](https://user-images.githubusercontent.com/6741099/44626329-34ec0f00-a955-11e8-8407-dc3bdcf27e33.png)

Most lags seem to be due to temperature calculation during block update and living entity update. Therefore I added the following config to core.cfg. They are probably effective in reducing lag.
- Block and Entity Blacklist for invalid from climate update
Excluded objects do not calculate the climate at update tick.
- "Enable Mob Climate Damage"
If this setting turned off, it limits the effect of climate damage to players only.
- "Entity Update Interval"
This setting changes the update interval of Entity's climate calculation. (So the interval of occurrence of climate damage changes.)

I appreciate you and the good mod you introduced!
