### ISSUE TITLE
issues with galacticraft/extra planets

### ISSUE THREAD

**Issue by paradoxmeem** [defeatedcrow/HeatAndClimateMod#77]
flickers between different biomes/planets, typically the proper biome and then Triton, occasionally another biome from another planet may pop up
can provide screenshots if needed

**Comment by defeatedcrow** [comment]
Could you tell me the version of Forge and that mod you used?
I need to test in my environment to investigate the problem.
Thank you!

**Comment by paradoxmeem** [comment]
forge version 2808/latest version on forge site. same for the heat and climate mod. i can't recall the extra planets version nor the core, but micdoodlecore, galacticraft core and galacticraft are version 190.

**Comment by defeatedcrow** [comment]
As a result of my test, HaC seems to have no problem.
Forthe  biome display data, HaC is acquiring player coordinates and biomes on the MC client. The flicker you found occurred because the client's biome information is actually unstable.
(Perhaps the instability on the client affects drawing only, I think that there is no harm in game play.)
