### ISSUE TITLE
ICY biome from Zoesteria Biomes shows up as 'hot'

### ISSUE THREAD

**Issue by viceroy369** [defeatedcrow/HeatAndClimateMod#81]
The White Woods/Christmas Woods biome from Zoesteria incorrectly displays as hot:

https://ibb.co/QKLSSqr

Even though it appears to be correctly registered as ICY:

https://github.com/valoeghese/Zoesteria/blob/master/src/main/java/valoeghese/valoeghesesbe/init/ModBiomes.java

**Comment by defeatedcrow** [comment]
Is there a high temperature block nearby? In such a case, if it is a local change, I think there is a lava lake under the ground.

**Comment by viceroy369** [comment]
No there isn't any local source, and every 'White Woods' biome says it's hot....heat and climate acts as if it's a desert biome.

**Comment by viceroy369** [comment]
https://ibb.co/Qkdms1f

**Comment by defeatedcrow** [comment]
In my test world, it worked normally. There is no problem with either HaC or Zoesteria.
Is not there a problem with your playing environment? Please check the possibility of conflicting Biome's numeric ID. (It should have an upper limit of 256.)

![2019-02-17_17 31 16](https://user-images.githubusercontent.com/6741099/52910528-17807800-32dc-11e9-82ed-5ea5ae8fa8eb.png)
![2019-02-17_16 32 24](https://user-images.githubusercontent.com/6741099/52910533-1b13ff00-32dc-11e9-895b-e95da3a1b2ad.png)

**Comment by viceroy369** [comment]
I have more than 256 biomes but I'm using mod Just Enough ID's which removes the ID cap and should auto-assign biome id's so that is odd.

**Comment by defeatedcrow** [comment]
It has already been confirmed that there is no problem with the combination of HaC and Zoesteria. Therefore, in order to identify the problem you need to find out the difference between my test environment and you. This is not a problem the author should undertake.

**Comment by defeatedcrow** [comment]
In addition: Automatic numbering of ID values using JEID should understand that the result will change with the introduction MOD change. In automatic number assignment, in ancient Mod Play, BlockID etc. caused similar problems frequently. Their use is self-responsibility.

Also, the screen shot presented by you suggests that HaC temperature is "display only" HOT and server side is COLD. (Because snow and ice are not melting.)
This is a typical server client registration data inconsistency, remembering corruption of saved or world data.
