### ISSUE TITLE
Smelting process of vanilla blocks doesn't seem to work

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#87]
I'm trying to add CraftTweaker support to HAC, thus I'm trying to use those interfaces to add some recipes for testing purpose. Other machines like Hammer Mill or Reactor works out well, but the problem comes when I added a smelting recipe -- it just can't process. The block didn't convert to the output  even after 30 mins and more until now.
![TIM截图20190324231724](https://user-images.githubusercontent.com/24620047/54881437-fe468a80-4e8a-11e9-9dfd-9eeca2f8a0ac.jpg)

I thought it was some sort of my fault at first, but other recipes that use vanilla block, like coal block -> coke block or dirt -> dried dirt, is not valid too.
Using 3.0.0

**Comment by Prunoideae** [comment]
ah, drop item entity was a code change after the problem occured, it may lead to a misunderstanding of the issue = =|||

**Comment by defeatedcrow** [comment]
This mod uses the naturally occurring Block Tick Update. So, if you add a recipe to a block that doesn't have the tick update feature (as in this figure), no change occurs.
I guess, this is by design of the core part of this game to reduce PC load by preventing unnecessary block updates. 
Recipes for blocks that do not have tick updates are usually displayed as "Less Frequency Process" on JEI. 

In order to advance these, please use the Conveyor Belt of HaC. Conveyor Belt have the ability to force items on them to change. This is a device prepared to aid in climate smelting.

**Comment by Prunoideae** [comment]
Fine, I may should add some comments in my mod to tell modpack makers about this...

**Comment by defeatedcrow** [comment]
Currently, by setting "Enable Vanilla Block Recipe" to "true" in the core.cfg of the configuration, a function is implemented to force random update of blocks near the player. Although it is less certainty, it may serve your purpose.

****
There are several other ideas (eg, flagging a scheduled update in a block placed by the player), but neither method is unfortunately less certain, and is not the concept of this mod. (It has not achieved naturally change that does not require operation by player). And these increase the PC load ...

I will consider this issue in the long run for the future. Thank you for your feedback.
