### ISSUE TITLE
[Suggestion] Please add List<ItemStack> analysis in FluidCraftRecipe

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#89]
Yep, I'm still working on the development of integration between HAC and CT, Mills and Spinning Machine was fully supported but the problem is that I can't pass a list of items to the constructor of FluidCraftRecipe, which caused a result that using OreDictionary while specifying the amount of items will be consumed.
![TIM截图20190325180832](https://user-images.githubusercontent.com/24620047/54911258-05bc7100-4f29-11e9-83bf-f7d79db21915.jpg)
Using strings can of course be a solution, but the amount of items will be consumed is impossible to specify.

Just like what the crusher can do:
![image](https://user-images.githubusercontent.com/24620047/54911368-4caa6680-4f29-11e9-8ecf-2cdc87c95130.png)

Only a suggestion :-P

**Comment by Prunoideae** [comment]
Here's my code process:
![TIM截图20190325181411](https://user-images.githubusercontent.com/24620047/54911628-d8bc8e00-4f29-11e9-8cbc-8e8d4c16c2a3.jpg)
I created a private list of list<ItemStack>, adding every input Ingredient to it by using Primer.addInput, and the code will retrieve every item of the dictionary and set amount of it, then pass it to the construction of FluidCraftRecipe in Primer.ignite():
![image](https://user-images.githubusercontent.com/24620047/54911830-45d02380-4f2a-11e9-8f5e-b742ece3d9a1.png)
And that's where the problem occurred.
![image](https://user-images.githubusercontent.com/24620047/54911983-8e87dc80-4f2a-11e9-9de4-019da1c769a9.png)

**Comment by Prunoideae** [comment]
well, using inputs.toArray() doesn't help anything at all, I though the problem is that List itself was recognized as only one variable, but changing this doesn't help.

**Comment by Prunoideae** [comment]
![TIM截图20190325182850](https://user-images.githubusercontent.com/24620047/54912584-dce9ab00-4f2b-11e9-9078-1d4230b44c0d.jpg)
![TIM截图20190325182840](https://user-images.githubusercontent.com/24620047/54912583-dce9ab00-4f2b-11e9-829f-272a0bdf6d80.jpg)
Using string to represent oredictionary is usable, but not good enough because the item count is always limited to 1......

**Comment by Prunoideae** [comment]
well, every machine except spinning machine only take one item each operation... that's a problem needs to be solved also :-(

**Comment by defeatedcrow** [comment]
Liquid  Crafting devices (the pot and chemical reactor) consume only one material per slot. Those machines, (like vanilla stove,) can not change the consumption by recipe registration because the consumption of the item is specified as 1 as a constraint on the implementation of TileEntity.

As these machines have multiple input slots, if the recipe has consumption of 2 or more, often "fractional items" will remain in the slots, which hinders the automatic operation of the machine. These were tested and deleted features because they were stressful to me in test play. There are no plans to change specifications in the future.

**Comment by defeatedcrow** [comment]
If you would like to propose another machine and recipe, please make another issue. They differ in the cause and topic of the issue.

**Comment by Prunoideae** [comment]
OK, if it's a preserved feature, there's no reason for me to change it.

**Comment by defeatedcrow** [comment]
The problem is distributed.
What is your request?

My answer is
- There are no plans to change the for "liquid recipe" consume amount.
- About other machines that have only one input slot can be considered. (It takes time because they require redesign of the machine)

The issue was aborted with insufficient conversation. Are you really ok with this?

**Comment by Prunoideae** [comment]
Well, if other machines are ok, then I think it's good to make things more flexible.
Though my first purpose was just to make liquid recipe consume specific amount, but that's not a big deal.

**Comment by defeatedcrow** [comment]
OK, I'll consider it about other machines.
I'm sorry about the liquid recipe.
